"""Drop the unused item table

Revision ID: 6b4344974fb8
Revises: dc304df8db88
Create Date: 2026-08-31 16:39:26.086449

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6b4344974fb8"
down_revision = "dc304df8db88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_description"), table_name="item")
    op.drop_index(op.f("ix_item_id"), table_name="item")
    op.drop_index(op.f("ix_item_title"), table_name="item")
    op.drop_table("item")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name=op.f("item_owner_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("item_pkey")),
    )
    op.create_index(op.f("ix_item_title"), "item", ["title"], unique=False)
    op.create_index(op.f("ix_item_id"), "item", ["id"], unique=False)
    op.create_index(op.f("ix_item_description"), "item", ["description"], unique=False)
    # ### end Alembic commands ###
