apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-worker-deployment
  labels:
    app: users-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-worker
  template:
    metadata:
      labels:
        app: users-worker
    spec:
      containers:
        - name: users-worker
          image: users-worker
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
